# Generated by Django 3.1.5 on 2021-02-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altura', models.FloatField()),
                ('equis', models.FloatField()),
                ('ye', models.FloatField()),
                ('zeta', models.FloatField()),
            ],
        ),
    ]
