# Generated by Django 3.1.5 on 2021-02-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformacion',
            name='altura',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='equis',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='latitud',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='longitud',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='ye',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='transformacion',
            name='zeta',
            field=models.FloatField(blank=True),
        ),
    ]
